### ISSUE TITLE
Unable to Set fan min on time.

### ISSUE THREAD

**Issue by rbflurry** [nkgilley/python-ecobee-api#15]
Hello, I apologize if this should be a home assistant issue or not But I am unable to set the min fan time.

This is the message I get in home assistant. If I should open a case over there please let me know.

```
2017-09-01 15:48:36 ERROR (Thread-6) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 1030, in execute_service
    service_handler.func(service_call)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/climate/ecobee.py", line 72, in fan_min_on_time_set_service
    thermostat.set_fan_min_on_time(str(fan_min_on_time))
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/climate/ecobee.py", line 361, in set_fan_min_on_time
    self.thermostat_index, fan_min_on_time)
  File "/root/.homeassistant/deps/lib/python3.4/site-packages/pyecobee/__init__.py", line 202, in set_fan_min_on_time
    return make_request(body, log_msg_action)
NameError: name 'make_request' is not defined
```

**Comment by nkgilley** [comment]
You need to update home assistant to 0.52.1

**Comment by rbflurry** [comment]
Great thank you.
